### ISSUE TITLE
Is it possible to make the default off?

### ISSUE THREAD

**Issue by jchian** [igorlogius/mute-unfocused-tabs#4]
Hey want to use this extension only certain occasions(like when having multiple twitch streams open) rather than it being the default behavior. Is it possible? Thanks!

**Comment by igorlogius** [comment]
If i understand you correctly you want to "invert"  the current behaviour. 
Aka explicitly mark the tabs to be managed and leave the others unmanaged.
Have to check if that is something that makes sense to add and how much effort that would involve. 
I'll be back.

**Comment by igorlogius** [comment]
That wasn't as easy as i thought it would be ... but AFAICT it seems to work.  
I'll release the version to AMO later. 

You'll find the `Manual Mode` option on the addon `Preferences` page.
Just check it and then goto to the tabs you want to have managed and toggle the toolbar button state to "ON".

Please Note: 
The selected tabs are AFAIK not persistent between browser sessions. 
So closing any tabs, window or the browser will remove all relations which were manually created.
mmm, ... writing this i could kind of see that it now also would make sense to add a kind of includsion  list  to allow users to set auto managed sites.  - Guess that would be kind of useful ... but i am lazy so  i'll wait until sombody ask for it. 
And obviously you are happy, since your inital request said nothing about this.  :-)  

Screenshot: 
![capture-2022-06-18_17:18:53](https://user-images.githubusercontent.com/67047467/174445016-f49720ff-0809-4688-9b1d-c23059090709.jpg)

**Comment by jchian** [comment]
Thank you sir for the prompt answer O.O, this was exactly what I wanted, having the inclusion list would be the cherry on top. xD
